### ISSUE TITLE
findCompletedItems returns undefined

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#48]
Hello, I observed `findCompletedItems` work **once** and then after I constantly get `undefined`.

Here is my code:

```
// set OAuth2 eBay credentials
eBay.auth.oAuth2.setCredentials(ebayAuthToken);

let post = {
  RequesterCredentials: {
    eBayAuthToken: ebayAuthToken
  },
  categoryId: categoryId,
  itemFilter: {
    name: `SoldItemsOnly`,
    value: true
  }
}

try {
let result = await eBay.finding.findCompletedItems(post)

console.log('result...')
console.log(result)
res.json(result)
} 

catch(e) {
  console.log(`Got error: `, e)
  res.json({error: e})
}
```

Is there any issue you can see with the code or is there an issue with this call?

**Comment by dantio** [comment]
Hey, I found the bug that cause it. But it's a error thrown from eBay.
Can you run your script with env "DEBUG=ebay:*". You will see the the real error.
I'll fix the bug in the mean time.

**Comment by doverradio** [comment]
Hi, sorry, where do I put this "DEBUG=ebay:*"?

**Comment by dantio** [comment]
DEBUG=ebay:* is an environment variable Something like `DEBUG=ebay:* node app.js` or `DEBUG=ebay:* npm run start`
You could also use the next branch https://github.com/hendt/ebay-api/tree/next where I already fixed this issue.
I'll merge it as soon as reviewed and tested it well.

**Comment by doverradio** [comment]
Hello, it appears this problem is back again. 

I ran this script and constantly get `undefined` as a result:
```
// express.js endpoint...
exports.findCompletedItems = async (req, res) => { 

  let a = {}
  let {
    categoryId,
    buyerPostalCode,
    paginationInput,
    sortOrder,
    user,
  } = req.body
  let userDoc = await User.findById({_id: user})
  eBay.auth.oAuth2.setCredentials(userDoc.token[0]) // set OAuth2 eBay credentials
  let post = {
    categoryId: categoryId,
    buyerPostalCode: buyerPostalCode,
    paginationInput: paginationInput,
    sortOrder: sortOrder,
  }
  try {
    let result = await eBay.finding.findCompletedItems(post)
    console.log('result...')
    console.log(result)
    res.json(result)
  } 
  catch(e) {
    console.log(`Got error: `, e)
    res.json({error: e})
  }  
}

```

Also, I tried to run `DEBUG=ebay:* node app.js` but it did not work and still I got `undefined` as a result.

**Comment by dantio** [comment]
That's strange. What version do you use? I only tried with keywords but not with the other parameters and it works fine.
Maybe it's related to this:
> Note: This call is deprecated as of October 15, 2020, and access is restricted. An alternative to findCompletedItems call is the Marketplace Insights API, but please note that this API is also restricted and requires eBay Business approval for access. Please contact the Developer Technical Support team if you are interested in getting access to the Marketplace Insights API.

**Comment by doverradio** [comment]
Sucks.  Have you implemented this Marketplace Insights API?

**Comment by dantio** [comment]
Yes. https://github.com/hendt/ebay-api/blob/master/src/api/restful/buy/marketplaceInsights/index.ts
However, I never tested it.

It's very strange that `undefined` is returned.

Could you test it like this: 
```js
let result = await eBay.finding.findCompletedItems(post, {raw: true})
```

Did you saw any debug information with DEBUG=ebay:* node app.js ?

**Comment by dantio** [comment]
@doverradio any update on this issue?

**Comment by doverradio** [comment]
Due to curiosity, just ran the `findCompletedItems` call again.

Same result: 
1. Ran request, got raw data like shown above in my earlier post
2.  Ran request a second time, 30 seconds later, got `undefined` result.

**Comment by doverradio** [comment]
Ok since I updated to the latest version of the library, I am finally getting something other than `undefined`.

Here is what I receive now after quickly making the second call...
```
{
    "error": {
        "message": "Service call has exceeded the number of times the operation is allowed to be called",
        "description": "",
        "stack": "EbayApiError: Service call has exceeded the number of times the operation is allowed to be called\n    at checkEBayResponse (C:\\Users\\User\\DesktopXXXXXXX\\backend\\node_modules\\ebay-api\\lib\\errors\\index.js:204:15)\n    at XMLRequest.request (C:\\Users\\User\\DesktopXXXXXXX\\backend\\node_modules\\ebay-api\\lib\\api\\traditional\\XMLRequest.js:183:48)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Traditional.request (C:\\Users\\User\\DesktopXXXXXXX\\backend\\node_modules\\ebay-api\\lib\\api\\traditional\\index.js:175:20)\n    at async Object.findCompletedItems (C:\\Users\\User\\DesktopXXXXXXX\\backend\\node_modules\\ebay-api\\lib\\api\\traditional\\index.js:43:24)\n    at async exports.findCompletedItems (C:\\Users\\User\\DesktopXXXXXXX\\backend\\controllers\\ebay.js:9863:20)",
        "type": "EbayApiError",
        "meta": {}
    }
}
```

**Comment by dantio** [comment]
I hope eBay Forum can Help in this Case :/

**Comment by dantio** [comment]
@doverradio Were you able to solve this problem?

**Comment by doverradio** [comment]
Hello, sorry for the long late reply on this.

I was never able to solve this through the API.  

Instead, I ended up using python scrapy to create a custom scraper using selenium.  It takes in any text query, opens ebay in a headless browser, then searches using the actual ebay search box.  After results come, it moves the mouse to click on "Sold only".  Only after this step, it scrapes all the results and returns them to me.

(Not sure if many people on here python but if contacted, I can share the script)

I'm sorry that may not be the answer you wanted, but it's the best I could do on overcoming how to obtain the completed and sold only items.  

Do you know of a better way?  Please share it if you do!

Thank you!
